### ISSUE TITLE
TypeError: read() got an unexpected keyword argument 'ignoregamma'

### ISSUE THREAD

**Issue by HuaYuXiao** [HuaYuXiao/NeRF#1]
```
/home/hyx020222/anaconda3/envs/NeRF/bin/python run_nerf.py --config config_fern.txt 
Traceback (most recent call last):
  File "run_nerf.py", line 928, in <module>
    train()
  File "run_nerf.py", line 590, in train
    spherify=args.spherify)
  File "/home/hyx020222/mapping_ws/src/NeRF/load_llff.py", line 246, in load_llff_data
    poses, bds, imgs = _load_data(basedir, factor=factor) # factor=8 downsamples original imgs by 8x
  File "/home/hyx020222/mapping_ws/src/NeRF/load_llff.py", line 114, in _load_data
    imgs = imgs = [imread(f)[...,:3]/255. for f in imgfiles]
  File "/home/hyx020222/mapping_ws/src/NeRF/load_llff.py", line 114, in <listcomp>
    imgs = imgs = [imread(f)[...,:3]/255. for f in imgfiles]
  File "/home/hyx020222/mapping_ws/src/NeRF/load_llff.py", line 110, in imread
    return imageio.imread(f, ignoregamma=True)
  File "/home/hyx020222/anaconda3/envs/NeRF/lib/python3.7/site-packages/imageio/__init__.py", line 97, in imread
    return imread_v2(uri, format=format, **kwargs)
  File "/home/hyx020222/anaconda3/envs/NeRF/lib/python3.7/site-packages/imageio/v2.py", line 360, in imread
    result = file.read(index=0, **kwargs)
TypeError: read() got an unexpected keyword argument 'ignoregamma'

Process finished with exit code 1
```

**Comment by HuaYuXiao** [comment]
- https://blog.csdn.net/qq_46684028/article/details/132722953
